### ISSUE TITLE
Receiving Unable to parse config file. Not starting. Syntax error on line 23

### ISSUE THREAD

**Issue by bryansampson** [yacht7/docker-openvpn-client#3]
Hi,

I'm hoping you can help. I'm not sure if this is an issue with the docker or not. Reading through the other issues has helped me resolve the DNS timeout issue I was getting, but now I can't get past this syntax error. Line 23 in my openvpn.conf is: remote-random.  I've tried commenting it out and removing it altogether, but I still keep getting syntax error on line 23. I even tried using @citrixscu's config and just changing the server addresses to LAX, with the same results.

Here's my openvpn.conf: https://pastebin.com/XUFpAZu7
Here's my log file: https://pastebin.com/R992xWYj

Thank you for your time

**Comment by bryansampson** [comment]
Sorry, it looks like it's not an issue with the docker image, but rather my stack config.  The docker is working correctly.

**Comment by yacht7** [comment]
Did you figure out the issue? I'm a bit curious to know why this would happen.

**Comment by bryansampson** [comment]
No, actually. I'm still getting the syntax error message in the log.  I was able to confirm that the docker is connected to the VPN, and I confirmed my qbittorrent docker is connecting through the vpn as well, however I can't access the web interface of qbittorrent even though I have the port published with -p 8080:8080 in the openpvn docker.  I've tried accessing it via the host's IP as well as the openvpn's IP

**Comment by jakopako** [comment]
I encountered a similar error message.

```
sed: unsupported command f
ERROR: Syntax error on line 5
Unable to parse config file. Not starting.
```
The reason was that [this line](https://github.com/wfg/docker-openvpn-client/blob/ea0b4dd271170005e7d77efd029b625e442259e2/data/scripts/tinyproxy_wrapper.sh#L10) spit out multiple IP addresses (ipv4 & ipv6) separated by newlines which made `sed` crash and hence caused the config file for tinyproxy to be invalid.

I am going to suggest a change in a pull request.

**Comment by wfg** [comment]
@jakopako can you share the output of `ip a show dev $1` that caused this?

**Comment by jakopako** [comment]
Sure!
```
20: eth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:1::242:ac11:2/64 scope global nodad
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link
       valid_lft forever preferred_lft forever
```
I guess this is because I have IPv6 enabled in docker.

**Comment by wfg** [comment]
Thanks, that's exactly why. :)

Can you see if this works for you?
```bash
addr_eth0=$(ip address show eth0 | grep 'inet ' | awk '{split($2, inet, "/"); print inet[1]}')
addr_tun0=$(ip address show tun0 | grep 'inet ' | awk '{split($2, inet, "/"); print inet[1]}')
```
Notice the space after `inet` in the `grep` command. (And if it does, go ahead and update your PR with it and I'll merge)

**Comment by jakopako** [comment]
It works. I'll update my pull request :)
