### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by Miosame** [yacht7/docker-openvpn-client#4]
I came here from the original mullvad docker hub entry - would it be possible to push this to hub too, for easier pulling instead of having to pull from git?

**Comment by yacht7** [comment]
Yep, it's already there:
[`docker pull yacht7/openvpn-client`](https://hub.docker.com/r/yacht7/openvpn-client)

**Comment by Miosame** [comment]
Oh, when I searched it just returned 404, thanks!
