### ISSUE TITLE
add bash?

### ISSUE THREAD

**Issue by bobbyrc** [yacht7/docker-openvpn-client#7]
Hi!
Was looking for a simple docker container to forward other container's traffic through using Mullvad, and came across your image. Thanks for putting this together and making it available.

Was just curious, have you considered installing bash on top of alpine to make it easy to check the public IP of the container?
I usually docker exec into my current solution and `curl icanhazip.com` to check the ip, which is super easy and doesn't require connecting another container just to check.

Just a thought! Thanks again!

**Comment by yacht7** [comment]
@bobbyrc Glad you find it useful, and thanks for the feedback!

To answer your question, it's obviously possible to add `bash`, but I don't find it necessary. Alpine has `ash` out of the box which is capable of doing what you're trying to do. That said, if you do find something `ash` isn't capable of, let me know and I'll reconsider.

This image doesn't have `curl` installed, so you'll have to use `wget` instead. Your command would look like this:
```
$ docker exec vpn wget -qO - icanhazip.com
```
or if you prefer to attach to the container first:
```
$ docker exec vpn ash
# wget -qO - icanhazip.com
```
`-qO -` flags tell `wget` to run quietly and write output to stdout

**Comment by bobbyrc** [comment]
Ah, I wasn't aware of ash!
Thank works for me. Thanks for taking the time to explain and provide an example! Will be super helpful for the future.
