### ISSUE TITLE
How to handle container restarts with other containers?

### ISSUE THREAD

**Issue by frumpymoons** [yacht7/docker-openvpn-client#8]
Containers that use network_mode: service:openvpn-client lose connection to the openvpn container when the openvpn container is restarted or recreated.

Usually that doesn't happen often because there is no need to restart or recreate it.

There is another case were the same problem occurs I think. When restarting all containers at once. Probably because openvpn should be the first one to be fully up inside the container but the others are faster and a reference changed that can only be fixed by restarting.

This is just my observation and theory I am no expert with this stuff.

Is there a way to prevent this from happening?

**Comment by yacht7** [comment]
To my knowledge, this problem only happens if the VPN container is removed after the other containers are created and is not unique to this image.

> There is another case were the same problem occurs I think. When restarting all containers at once. Probably because openvpn should be the first one to be fully up inside the container but the others are faster and a reference changed that can only be fixed by restarting.

I haven't seen this happen using Compose. Having `network_mode` set seems to guarantee that my containers using the VPN are created after the VPN container.

**Comment by frumpymoons** [comment]
I found this issue at the compose github: https://github.com/docker/compose/issues/6626
This seems to be me my problem. I will try to make it work with the mentioned workaround.
